### ISSUE TITLE
No interactables on stage

### ISSUE THREAD

**Issue by Squydy** [Moffein/Maximum_Cope#1]
When starting a new run there were no interactables on the stage at all. No teleporter, shrines, chests, or newt altars. This also happened towards the end of the run on stage 5. We were able to leave the stage using the artifact portal, and after completing that it returned us to a normal stage 5. I generally run at solid 120fps if that's helpful at all. Don't have a log for this one, sorry

**Comment by Moffein** [comment]
Next time the issue happens (or if you haven't booted up the game since the last time you saw the issue), could you send your log file over so I can take a look?
You can find it by going to r2modman -> settings -> locations -> browse profile foler -> BepInEx/LogOutput.log

**Comment by Squydy** [comment]
Remembered to save the log this time
[LogOutput.log](https://github.com/user-attachments/files/16882795/LogOutput.log)

**Comment by Moffein** [comment]
StageAesthetic is breaking stage startup.
Create a completely fresh mod profile that only contains mods updated after SotS.

**Comment by Squydy** [comment]
Saw the errors for that as well so it seems plausible
